name: Build

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.5.0-jdk17-alpine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

  build-docker:
    runs-on: ubuntu-latest

    needs: build-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

      - name: Build Docker Image
        run: |
          docker build -t fiapi-hackaton-relatorios .
